version: '2'
services:
    bolg-mongodb:
        container_name: bolg-mongodb
        image: mongo:3.3.5
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/bolg/mongodb/:/data/db/
